trigger:
  branches:
    include:
    - refs/heads/docker

variables:
  imageName: 'e2e-sanity-tests-azure'
  dockerfile: 'Dockerfile'
  gitRepo: 'https://github.com/haris124421/LIO-FX-TP10.git'
  branchName: 'docker'
  dockerRegistryEndpoint: 'my-docker-registry'
  CYPRESS_BASEURL: 'http://192.168.122.191:7585'
  CYPRESS_USERNAME: 'haris'
  CYPRESS_PASSWORD: 'Test1'
  CYPRESS_BUILD: '5.9.0.12'

stages:
- stage: Build
  displayName: Build Docker Image for cypress
  jobs:
  - job: BuildDockerImage
    displayName: Build Docker Image
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: 'build'
        dockerfile: '$(dockerfile)'
        context: '$(Build.Repository.Name)'
        tags: '$(imageName):latest'

- stage: Test
  displayName: Test
  dependsOn: Build
  jobs:
  - job: RunCypressTests
    displayName: Run e2e Tests
    pool:
      name: Default
    steps:
    - script: |
        npm run e2e
      workingDirectory: '$(System.DefaultWorkingDirectory)/app'
      displayName: 'Run Cypress Tests'
